### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by s2339956** [charlie0227/crawler_shopee#1]
Init driver done.
[INFO] pop modal not found
[INFO] cookie.pkl not found
[INFO] Login Failed
[ERROR] Login Modal not showingWebDriverException('unknown error: Element <li class="navbar__link navbar__link--account navbar__link--tappable navbar__link--hoverable navbar__link-text navbar__link-text--medium">...</li> is not clickable at point (1182, 17). Other element would receive the click: <div class="shopee-popup__overlay"></div>\n  (Session info: headless chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.9.184-linuxkit x86_64)', None, None)
Traceback (most recent call last):
  File "main.py", line 85, in loginByPass
    login_button = self.driver.find_elements_by_css_selector(".navbar__link--account")[1].click()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <li class="navbar__link navbar__link--account navbar__link--tappable navbar__link--hoverable navbar__link-text navbar__link-text--medium">...</li> is not clickable at point (1182, 17). Other element would receive the click: <div class="shopee-popup__overlay"></div>
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.9.184-linuxkit x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
    a.loginByPass()
  File "main.py", line 89, in loginByPass
    self.exit()
AttributeError: 'Crawler' object has no attribute 'exit'

**Comment by a10charliec** [comment]
Thanks for the reports
Have fixed in  2041ef9873ee92aef1c6eb258610a705775bfad8

**Comment by charlie0227** [comment]
Thanks for the reports
Have fixed in  2041ef9873ee92aef1c6eb258610a705775bfad8
