### ISSUE TITLE
Error Login Modal not showingTimeoutException

### ISSUE THREAD

**Issue by s2339956** [charlie0227/crawler_shopee#2]
Init driver done.
[INFO] pop modal close
[INFO] cookie.pkl not found
[INFO] Login Failed
[ERROR] Login Modal not showingTimeoutException('', None, None)
[INFO] Program exit

**Comment by kirbyloco** [comment]
@s2339956 
open main.py file and change ".shopee-modal__content" to "._2GJ_OW.undefined"

**Comment by s2339956** [comment]
> @s2339956
> open main.py file and change ".shopee-modal__content" to "._2GJ_OW.undefined"

Thanks, this method works

**Comment by s2339956** [comment]
[main.py:136 -        checkPopModal() ] 2020-04-28 01:23:18,934 root         INFO     pop modal close
[main.py:155 -        loginByCookie() ] 2020-04-28 01:23:18,939 root         INFO     cookie.pkl not found
[main.py:146 -           checkLogin() ] 2020-04-28 01:23:24,037 root         INFO     Login Failed
[main.py:164 -          loginByPass() ] 2020-04-28 01:23:29,253 root         ERROR    Login Modal not showingTimeoutException('', None, None)
[main.py:256 -                close() ] 2020-04-28 01:23:29,361 root         INFO     Program exit
